### ISSUE TITLE
[Example Issue] Should we use geoJSON in the Registers project

### ISSUE THREAD

**Issue by torgo** [alphagov/tech-and-data-standards#1]

**Comment by torgo** [comment]
@daverog any input from MoJ perspective?

**Comment by torgo** [comment]
test comment

**Comment by torgo** [comment]
test comment

**Comment by torgo** [comment]
cf https://github.com/datagovuk/ckanext-spatial

**Comment by torgo** [comment]
Testing the new Slack integration.

**Comment by PeterParslow** [comment]
Good idea. But need to be clear on which geoJSON you mean: as noted at http://geojson.org/, IETF RFC 7946 has now (as of August 2016) replaced the 2008 specification. Obviously, not much software has adjusted to that yet.
As usual with 'standards', there are subtle differences, which don't matter much of the time - but suffer the general weakness of JSON: no 'standard' way to state a version or semantics. And therefore, not entirely stateful / capable of being used in an entirely stateless transaction - by which I mean the consumer of a JSON message needs some state context by which to interpret the data.

In particular, RFC 7496 GeoJSON can only include longitude, latitude coordinates based on WGS84. This means it can't reliably be used for anything more precise than 1m, and that the positions will degrade slowly over time (in UK, by ~1m / 40 years). That's usually good enough! But beware, there's plenty of "GeoJSON" data & software out there which expects coordinates in e.g. British National Grid. That's no longer allowed.

**Comment by edent** [comment]
At the moment, we've standardised on WGS 84 and ETRS89 as co-ordinate systems.

https://www.gov.uk/government/publications/open-standards-for-government/exchange-of-location-point

If there is a specific user need for geoJSON - whether in Registers or elsewhere - please open a new issue.

**Comment by PeterParslow** [comment]
If you don't use geoJSON, does that mean you are going to develop your own JSON vocabulary to express geography? Or some encoding other than JSON?

**Comment by edent** [comment]
No, we're not planning on developing our own vocabulary. The mission of the standards team is to find the appropriate Open Standard and approve its use.

If there's a specific area where we're using a closed standard, or no standard at all, please let us know.
