### ISSUE TITLE
Workshop Happening on the 18th of Feb

### ISSUE THREAD

**Issue by torgo** [alphagov/tech-and-data-standards#10]
Hi @alphagov/tech-standards - I am testing out the ability to notify a team on github and using that as an opportunity to remind you to register (if you have't done so already) for the workshop we're holding in the afternoon of the 18th of February - see https://ti.to/torgo/ukgov-standards-camp for registration info.

**Comment by JohnStrudwick** [comment]
Hi Dan

I gave James the names of some people at DVSA and DVLA - Have you spoken
with them as they were asking me when the event was - at the time I didn't
have the information to hand and said you or James would be in touch.

(DVSA: Peter Campbell & Darren Martin - Andrew Shapton ( who you met ) at
DVLA

Regards


*John *

**Comment by philandstuff** [comment]
resolved
