### ISSUE TITLE
Streaming multiple JSON documents

### ISSUE THREAD

**Issue by philandstuff** [alphagov/tech-and-data-standards#11]
There is a common need to stream multiple JSON documents, in such a way that you process each document one at a time rather than loading the whole stream in to memory. JSON itself is unsuitable for this type of processing.

There is a useful [wikipedia page on JSON Streaming](https://en.wikipedia.org/wiki/JSON_Streaming).

There are a number of competing independently-reinvented "standards" in this space:
- things which use the ASCII LF char as a separator:
  - [JSON Lines](jsonlines.org/)
  - [ndjson](https://github.com/ndjson/ndjson-spec) which can allow blank lines
- things which don't use any delimiter at all, relying on the JSON parser to find where one document ends and the next begins
- [RFC 7464](https://tools.ietf.org/html/rfc7464) which uses the ASCII RS (0x1e) char as a separator

The wikipedia page has a summary of existing use of each (of which, I'm most familiar with logstash and jq). I don't know if anyone uses RFC 7464 even if it has theoretical advantages - namely, that the RS byte cannot appear anywhere in a JSON byte stream.

**Comment by philandstuff** [comment]
A little research shows that [@moshez is using RFC7464 at Square](https://github.com/golang/go/issues/2981#issuecomment-162660214) (see also moshez/rfc7464 and moshez/rfc7464.rb), and that the [new geoJSON draft](https://github.com/geojson/draft-geojson/pull/132) has a reference to it. That's about all I could find.

**Comment by danielquinn** [comment]
When I worked at the [RIPE NCC](https://www.ripe.net/) on the [Atlas project](https://atlas.ripe.net/) we managed this with JSON lines and even with >100TB of data stored and fractionally streamed on-demand, our users seemed very happy.  It was also really easy to write software around.

**Comment by rboulton** [comment]
I've used JSON lines in several projects; as long as you control the encoding process, it is easy to ensure that the JSON in a line never has a line feed character. The benefits of being able to use standard unix tools to process line oriented data seem high, partly for exploratory coding, but also for easy partition of datasets into separate files, or for tailing of log files, etc.

I've never heard of anyone actually using "concatenated JSON".  The overhead of having to fully parse each record to move to the next record seems a high cost, for very little benefit.

**Comment by edent** [comment]
Closing this for now due to lack of use-case.  If I've misunderstood and there is a defined case, please open a new issue.
