### ISSUE TITLE
What HR data standards exist?

### ISSUE THREAD

**Issue by torgo** [alphagov/tech-and-data-standards#13]

**Comment by pmackay** [comment]
It would be handy to add a bit more info to this on the kind of scope it covers.

**Comment by heathd** [comment]
The government is trying to get a better view of its skills and capability across its workforce to help workforce planning. The need for this data has been highlighted in numerous reports such as [this one from the National Audit Office](https://www.nao.org.uk/report/central-government-staff-costs/).

What role can open standards play in facilitating interchange of data which would help workforce planning? Examples of such data:
- job ads/vacancies
- business objectives and KPIs
- staff objectives
- staff profiles, including skills/competencies
- projection of skills required by department
- organograms/staff heirarchies
- performance management
- frameworks for skills and competencies, including specialist/professional ones

How could open standards help us to avoid [lock-in](https://www.gov.uk/service-manual/making-software/choosing-technology.html#lock-in)?

An example of an open standards body working in this space http://www.hropenstandards.org/ however I have not researched them at all.

**Comment by jystewart** [comment]
Worth mentioning that the Open Standards Board is currently considering the schema.org job posting format - https://standards.data.gov.uk/challenge/publishing-vacancies-online

**Comment by kerin** [comment]
Seen on x-gov Slack:

https://medium.com/@charlesrt/setting-an-open-standard-for-job-postings-9e548f8fc9bd#.elfr5wifz

https://gist.github.com/charlesrt/75ab9768298cbd2466b7

**Comment by heathd** [comment]
The job standards are also in this repo as issue #8
