### ISSUE TITLE
API documentation standard

### ISSUE THREAD

**Issue by pmackay** [alphagov/tech-and-data-standards#15]
_Forked from #9:_

**Documentation** – We are favouring Swagger 2.0. There is a split between design first or use annotations in the code. What are others doing?

From @rossjones:

Are you aware that the swagger 2 spec is now forming the basis for the [OpenAPI initiative](https://openapis.org/)? The specification is currently available at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md it might cover more than a few of these items?

**Comment by pmackay** [comment]
Can anyone comment who ran the session at the standards workshop yesterday on documentation? I didnt catch who it was but getting their thoughts on why Swagger _wasnt_ so great would be useful.

I've personally worked with RAML on the [Waste standards](http://communitiesuk.github.io/waste-service-standards/) and its good for prototyping an API.

**Comment by philandstuff** [comment]
@pmackay I think you're talking about @ijmad

**Comment by RosalieDM** [comment]
Paul, are you aware of the API doc event we're holding on the 4 March?
http://www.meetup.com/Write-The-Docs-London/events/228403383/

We are hoping to have Swagger speak.

On 19 February 2016 at 09:57, Philip Potter notifications@github.com
wrote:

> @pmackay https://github.com/pmackay I think you're talking about @ijmad
> https://github.com/ijmad
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alphagov/tech-and-data-standards/issues/15#issuecomment-186145041
> .

## 

Rosalie Marshall
Technical Writer
Government Digital Service http://GOV.UK
07535686145

**Comment by andy-gray** [comment]
I really dislike the way swagger organises everything around URLs.
This encourages clients to template URLs and code directly to them.
Which all rather makes a mockery of the idea we want to use hypermedia.

This post (not mine) goes into more detail and suggests an interesting alternative.
https://restful.io/why-your-colleagues-still-don-t-understand-hypermedia-apis-bb45d77172c7#.q3vk3qb7j

**Comment by danielquinn** [comment]
I feel like this is a good time to bring up [CoreAPI](http://www.coreapi.org/).  It's a project being spearheaded by @tomchristie to effectively make communicating with all APIs easier.  He gave a talk at a local Django meetup this week and the project, while still quite young, is promising.

My understanding is that so long as you adhere to one of a few reasonably well-formed standards (OAI/Swagger2 among them), 3rd-party apps using the CoreAPI methodology will be able to interface with your data without having to know about the typical minutia associated with plugging into an API.

Anyway, if you're building an API anyway, this seems like a good project to keep in mind.

**Comment by lovelydinosaur** [comment]
Thanks for the mention @danielquinn. That's a pretty good summary. (The Core API front page documentation probably has some catching up to do in order to better explain the proposition.) And yes, the big sell is that it allows dynamic client libraries/tooling for interacting with APIs that expose either schemas and/or use hypermedia responses. Right now there a python client library and a command line client, with more stuff in the works.

**Comment by danielquinn** [comment]
I should also mention (for those of you not of Python-land) that @tomchristie is the primary developer behind the Django REST Framework, which is the de-facto platform for building REST APIs in Djangoland.

**Comment by pmackay** [comment]
@ijmad could you add any comments reflecting your views from the workshop?

@RosalieDM thanks! Have signed up.

@andy-gray @danielquinn I'm certainly in favour of a hypermedia approach. Is that a generally accepted goal in the development of new gov APIs? 

Also a view towards the end of the workshop session was it is probably good to have both docs and follow hypermedia principles. Does that seem reasonable? In which case it would be good to debate the pros/cons of documentation approaches.

**Comment by PlanetCJ** [comment]
We use Apiary as a documentation medium as well as a place to evaluate APIs. Its really useful for evaluating APIs prior to 'heavy' development. You can look at a sample one for the Skills Funding Agency here: 

http://docs.standardservice.apiary.io/#

This is the evaluation area we're using to develop the service contract for the new Apprenticeship Service. I didn't like swagger as much as Apiary as Apiary can be run completely in the cloud with a common URL that all your devs can use wherever they are. Apiary also provides a real URL for you to test against that you can use as a stub during mock testing.

**Comment by edent** [comment]
Now continuing in #31

Thanks for all your contributions.
