### ISSUE TITLE
schema.gov.uk

### ISSUE THREAD

**Issue by andy-gray** [alphagov/tech-and-data-standards#18]
Would a repository for type definitions in the same spirit as [schema.org](http://schema.org) be a worthy ambition?

Would you make use of it?
Would you contribute to it?
What style of presentation and what notations should it have?
Who would oversee? and what oversight model would work best : OSS, delegating sub schemas to departments, etc.
Who would pay?

**Comment by jystewart** [comment]
I'd want to understand what value we'd get from having our own vs. working with schema.org and similar initiatives directly. My experience to date has suggested that most of the time the things we wanted to do are best done in existing public forums.

The Open Standards Board is currently considering a schema.org standard for job postings - https://standards.data.gov.uk/challenge/publishing-vacancies-online

**Comment by hadleybeeman** [comment]
+1 to @jystewart's note of caution. Additionally, most of the "let's do this ourselves" efforts I've seen/been a part of, within gov, would have been vastly improved by bringing in people outside gov working on similar/the same problems.  I can't think of a single use case where we'd want to say, "Not only are we the only people facing this problem, we will never want to use new technologies/approaches to solve this, so there's no point in bringing in anyone who might be able to build a better way — now or in the future — to sort this." 

I think building for interoperability just has to involve others. It maximises the amount of take-up of the standard, which means there will be more tools we'll be able to use, which means we'll have more choices. Ideally, better choices.

(And also — established standards processes tend to introduce some rigour in thinking through use cases, not recreating existing wheels, avoiding nasty IP traps, promoting adoption,  etc.  They've generally learned the hard way how to navigate this stuff!)

**Comment by bradwright** [comment]
We're considering the Article and Periodical schema.org formats for GOV.UK
because of the easy compatibility it gives us with existing clients eg
Google Search.
On Wed, 24 Feb 2016 at 12:41, Hadley Beeman notifications@github.com
wrote:

> +1 to @jystewart https://github.com/jystewart's note of caution.
> Additionally, most of the "let's do this ourselves" efforts I've seen/been
> a part of, within gov, would have been vastly improved by bringing in
> people outside gov working on similar/the same problems. I can't think of a
> single use case where we'd want to say, "Not only are we the only people
> facing this problem, we will never want to use new technologies/approaches
> to solve this, so there's no point in bringing in anyone who might be able
> to build a better way — now or in the future — to sort this."
> 
> I think building for interoperability just has to involve others. It
> maximises the amount of take-up of the standard, which means there will be
> more tools we'll be able to use, which means we'll have more choices.
> Ideally, better choices.
> 
> (And also — established standards processes tend to introduce some rigour
> in thinking through use cases, not recreating existing wheels, avoiding
> nasty IP traps, promoting adoption, etc. They've generally learned the hard
> way how to navigate this stuff!)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alphagov/tech-and-data-standards/issues/18#issuecomment-188233719
> .
> 
> ## 
> 
> Bradley Wright

Head of Technology, Digital Group
Government Digital Service
@bradwright

**Comment by pmackay** [comment]
@bradwright do you have in mind a favoured markup approach (Microdata, RDFa, JSON-LD)?

**Comment by jabley** [comment]
[Spotlight is already using schema.org](https://github.com/alphagov/spotlight/commit/0bc8026f5fa00a4dd4b28de251610fc35ad3a7a4) on [the Performance Platform](https://www.gov.uk/performance/prison-visits).

**Comment by andy-gray** [comment]
The only real concern I have with working with schema.org directly for publishing gov-specific types is the speed of change - that job-vacancy schema looks like it's been in proposal for 2 years.

TBH I'm far more interested in the idea that we routinely publish all schemas, and have the skills and support available to ensure we can to it well... and only care where we publish to - if it impacts speed, quality or authoritativeness.

**Comment by edent** [comment]
For now, we're not interested in being the canonical repository. We will point to the standards body which publishes the standard.
