### ISSUE TITLE
What about SSO?

### ISSUE THREAD

**Issue by danielquinn** [alphagov/tech-and-data-standards#19]
I'm working (ever so painfully) to setup an auth chain using Azure Active Directory as the SSO service and believe me when I tell you that it's a huge hassle.

Do we have any established patterns around SSO?  Over here in UKTI Microsoft stuff appears to be the norm, and we've already got a few products using Azure AD, so that's why I have to integrate it, but I think we'd do well not to make a habit of this.

**Comment by philandstuff** [comment]
One option is SAML, which has a related issue #6. (This is not necessarily an endorsement of SAML).

We investigated OpenID Connect as part of an alpha investigating organisation identity at GDS. It's probably another option to consider.

**Comment by david-durant-gds** [comment]
The GDS Common Technology Services programme is designing a pattern for cross-gov SSO. They're working with folks from a number of different organisations. I've already mentioned to the person in charge there that this forum is a good place to continue that discussion. He's Peter Cummings (peter.cummings@digital.cabinet-office.gov.uk). Another good contact is the GaaP lead TA David Illsley (david.illsley@digital.cabinet-office.gov.uk).

**Comment by Lawrence-G** [comment]
This conversation has moved to #38
