### ISSUE TITLE
How do we namespace / identify json representations?

### ISSUE THREAD

**Issue by dhilton** [alphagov/tech-and-data-standards#20]
When dealing with a range of currently internal json interchange formats (@ONSDigital) we're pondering how / if to namespace and identify them as we create new data formats. Our current internal examples are survey schema's (how do you define a survey at a structural level, enabling a representation of that survey , be it a web experience, a voice IVR or a mobile app) and responses from the collection of data.

We're considering java style (uk.gov.ons.<SYSTEM_NAME>.<FILE_TYPE>) or some sort of mime-type style that would allow us to reuse it in APIs to set accept headers and response headers. 

In trying to find prior art, we haven't found much - be interested in any examples of adding such metadata to json files (specifically as some of this data will exist on large filesystems just as much as being served via API's)

For further context see this documentation PR here: https://github.com/ONSdigital/edc-documentation/pull/1

And comment on that https://github.com/ONSdigital/edc-documentation/pull/1/files#r55227838

**Comment by andy-gray** [comment]
Have you considered json-ld?
