### ISSUE TITLE
Elections data schema

### ISSUE THREAD

**Issue by MikeThacker1** [alphagov/tech-and-data-standards#22]
The LGA is leading work to produce a schema for CSV open data on election candidates and results.  The main discussion is in the Knowledge Hub thread [Election results schema second round consultation Aug-Oct 2016](https://khub.net/group/localopendatacommunity/forum/-/message_boards/message/26336391#_19_message_26336391) 

The consultation overview document (PDF) is http://e-sd.org/dmKwu

The latest version of the schema description is http://e-sd.org/vgTJ3

Comments can go in the above forum or by email to transparency@local.gov.uk.  Alternatively, I'll pass on anything posted here.

**Comment by edent** [comment]
Hi @MikeThacker1 - has there been any update to this? Any schemas published?

**Comment by MikeThacker1** [comment]
This is the Guidance Document issued by the LGA http://e-sd.org/vgTJ3  

I've just been asked to put a representation in our CSV schema validator at http://validator.opendata.esd.org.uk/

I'll post here when that is up.  I have a couple of related questions which I'll post here when the draft is up.

**Comment by MikeThacker1** [comment]
Hello

I don't think anyone has raised the LGA Elections Schema as a formal Challenge since the meeting with GDS on 2 Mar 2017. Should the LGA or I raise this as an issue in the same format  [Date-Times and Time-stamps Challenge](https://github.com/alphagov/tech-and-data-standards/issues/37) and others?

**Comment by Lawrence-G** [comment]
Hello Mike,
Thank you, yes please do use the 'new issue' button to raise the challenge. There's no obligation to then be the challenge owner.

**Comment by MikeThacker1** [comment]
Thanks Lawrence.  I've drafted an issue for review with LGA colleagues and hope to post really soon.

**Comment by MikeThacker1** [comment]
Raised as [Schema for data on election candidates and results - Challenge](https://github.com/alphagov/tech-and-data-standards/issues/42).
