### ISSUE TITLE
Rejected / On Hold Standards

### ISSUE THREAD

**Issue by edent** [alphagov/tech-and-data-standards#25]
As a proposer, I want to see which standards have been proposed which have _not_ been adopted. This will help me improve the quality of my submissions.

**Comment by edent** [comment]
Should be as closed issues?

**Comment by Lawrence-G** [comment]
it was possible to view the archive of rejected suggestions on mk1 Hub but this was lost in the 2015 refresh. I agree having a folder(or something) of rejects would be useful particularly if the comments/reasons for rejection were available. I can dig out the archive.
