### ISSUE TITLE
status of API to manage Ltd. companies

### ISSUE THREAD

**Issue by serapath** [alphagov/tech-and-data-standards#36]
# Create A Challenge

## Title
> status of API to manage Ltd. companies

## Category
- [ ] Data
- [ ] Document
- [ ] Technical
- [ ] Other Suggestions

## Challenge Owner
> I'm an activist and open source developers building elearning to teach underprivileged JavaScript with the goal of connecting them to remote JavaScript gigs to kickstart their open source and self-employment career.

## Short Description
> I would like to help people into self employment and the UK Ltd. seems to be a perfect vehicle, because it's easy to use and affordable. If there was an API to open, manage & close a Ltd. company, it would be a lot easier to build "business software" that directly connects and automates burueacracy which is the major hurdle for underprivileged people who just simply do not have the money and time and often background to cope with the traditional process of managing a Ltd.

## User Need
> The fear of trying self employment, especially the bureaucracy that comes with it are one of the major show stoppers for many people to even try themselves as little entrepreneurs. Having an API and all the support necessary will allow open source solutions to build tools that will help a variety of users to actually try their luck.

## Expected Benefits
> Many refugees that came to europe in the recent months and in general unemployed people or people with backgrounds that makes them a hard fit for traditional employment could go into self employment if there was an open source ecosystem of users and contributors that would help to pave the way.
It would mitigate all kinds of rational and irrational fears connected with trying oneself as an entrepreneur.
The major cost currently is filing annual accounts and hiring accountants especially in the beginning, when income is lacking or self employment is a little side project. Every pound or euro matters and an accountant makes more than 80% of all the costs that come with opening and managing the bureaucracy connected to a Ltd. company.

## Functional Needs
> A nice and easy to use API to open, manage and close a Ltd. company including documentation around how to use the API. HTTP would be great, but having some kind of subscribe machanism like hooks or websockets for real time updates wouldnt be bad

**Comment by Lawrence-G** [comment]
Thank you. There is certainly merit in the aim of encouraging and enabling self-employment among groups of people who would benefit from having their own company but are deterred by bureaucracy. Likewise to provide them with skills that are marketable.
This does not fit in with the work of the open standards team at GDS however. Here we are looking at scenarios where an existing open standard can be employed across government for software interoperability, data and documents formats.
It so happens that the digital team at companies house has an active [API development hub](https://developer.companieshouse.gov.uk/api/docs/index.html) and forum, which you may be aware of. The companies house API does not yet support creation the of companies, I notice, but it may be something that could be built in the future.
If we've misunderstood you and there is a specific standard, or standards you have in mind, then this suggestion could be framed on how a standard would meet user needs.

**Comment by serapath** [comment]
No, I was not aware of the API development hub, so maybe i continue there then.

Thank you :-)

**Comment by edent** [comment]
Glad we could help. I'll close this issue for now. If Companies House don't use an open standard for their API, you can open an new issue.
