### ISSUE TITLE
Report a Food Problem Open Standard

### ISSUE THREAD

**Issue by adamlocker** [alphagov/tech-and-data-standards#39]
# Create A Challenge

## Title
Report a Food Problem Open Standard

## Category
- [X] Data
- [ ] Document
- [ ] Technical
- [ ] Other Suggestions

## Challenge Owner
Adam Locker, Data Architect at the Food Standards Agency.

## Short Description
The FSA have a service where the public can report food problems, i.e. "I found a gnome in my soup" that sort of thing, providing details of the business, the issue and some limited details about themselves. The FSA then uses this information to work out the appropriate local authority who would investigate any problems and currently hand these off to the LA by email. We're currently in the process of rebuilding this service and we'd like to improve this by using a suitable open standard if possible.

## User Need
FSA would benefit from more automated transfer of data to local authorities, preferably with the ability to receive or request updates. An open standard would also help LAs share food problem data better between them.

## Expected Benefits
Reusing an open standard always preferable to creating a new one. Also, we could create a standard but it isn't really one without wide adoption. Why reinvent the wheel? Can you find us a wheel that works?

## Functional Needs
Not too restrictive on the fields we can pass to LAs.

**Comment by BforBen** [comment]
I wonder if using Open311 would work here but standardising the attribute model for the "Report a food problem" service?

http://wiki.open311.org/GeoReport_v2/#post-service-request

**Comment by edent** [comment]
Thanks @BforBen - Open311 looks interesting. Does anyone know of any government departments *already* using it?

**Comment by BforBen** [comment]
West Berkshire certainly do for some highways things - https://github.com/LocalGovDigital/localo/wiki/Civic-issue-tracking

**Comment by jukesie** [comment]
Any Councils who integrate with FixMyStreet already use Open311 so as well as West Berkshire - Bristol, Greenwich, Stirling and about a dozen others.
There is no reason why the standard couldn't work for this proposed use case - there remains a pretty active community for Open311 with a regular community call / mailing list etc.

**Comment by dhilton** [comment]
A 👍  for Open311 - Bath & North East Somerset are looking at this currently for reporting & managing local issues.

**Comment by edent** [comment]
We're still evaluating this. Our thought is to look for a *generic* standard for "report a problem to a government department".

**Comment by Lawrence-G** [comment]
We have decided that food problems would be a local government standard though we would still be interested in a generic problem reporting standard.
