### ISSUE TITLE
Understanding Government Information

### ISSUE THREAD

**Issue by Lawrence-G** [alphagov/tech-and-data-standards#41]
## Category
- [x] Data
- [ ] Document
- [x] Technical
- [ ] Other Suggestions

## Challenge Owner
This challenge was presented to the Open Standards Board by A. Seles from The National Archives
## Short Description
Government information is produced on many different platforms and can include things like records, emails and data. Users of government information, both citizens and government officials, need to be able to understand it and use it, independent of any platform, furthermore, users should be able to examine and query information without having access to its full contents. In order to accomplish this, government systems need to create a standardised set of information (i.e. metadata) about the resources it manages.

## User Need
Users in this context include citizens, civil society and government officials.

- Citizens: Standardising how government information is presented to citizens will allow them to understand how it was created, who created them and, in particular, how it was compiled including technical makeup and the original source material used to create it
- Government officials: A standardised set of metadata will allow government officials to understand the information in their systems, as well as facilitate the interchange between different government departments and civil society without loss of meaning or misinterpretation. Enabling more information exchange also promotes better collaboration across a number of different technological platforms.

Furthermore, having standardised metadata will also allow public officials to meet legislative requirements as information can be easily retrieved to answer access requests under Freedom of Information or transfer records to The National Archives, as per the Public Records Act.

## Expected Benefits
- Ease of retrieval and reduction in costs: Standardised metadata, utilising common vocabularies means that information can be queried, retrieved and collated with greater ease. This decreases the amount of staff time spent locating information and correcting data quality issues,  allowing for the identification of materials that can be destroyed, in accordance with legislative requirements, freeing up server space.  The benefits for government departments is that this optimises the usage of IT infrastructure whether onsite or offsite (i.e. Cloud)
- Collaboration and information exchange: Essentially documents can move freely between applications or organisations in a consistent way without the need for further effort or technology to be applied. Therefore, government departments can exchange information between systems, facilitating more collaboration because document metadata through clear and standardised categorisation along with subject identification enables users to know the subject matter of the contents prior to opening. This allows for greater efficiency of time and resources. 
- Meeting legislative requirements: Departments can search and research information in a more timely and effective manner for FOI access requests. Further it allows government departments to design better information handling practices as protective markings are clearly and accurately reflected, while also ensuring the consistent export of data or records from systems, which ensure that they information has integrity and enables greater automation of the transfer to The National Archives. 
- Compliance with Public Sector Information (PSI) Directives: Enable public bodies to share government information in a consistent and open method on with citizens to realise economic, societal and democratic benefits. For more information on the PSI Directives please see: http://www.legislation.gov.uk/uksi/2015/1415/contents/made

## Functional Needs
The solution to the challenge should be able to meet the following functional needs:
- Enable documents to transfer between technologies or between organisations without loss of meaning and understanding.
- Allow organisations to meet the statutory requirements to dispose of documents that no longer need to be kept.
- Be extensible to allow future changes and additions by users for their own business needs and use cases.
- Be machine processable within the application and workflows where documents are created, held and shared.

**Comment by philarcher** [comment]
This challenge is a close match to the work of the newly launched [W3C Dataset Exchange](https://www.w3.org/2017/dxwg/) WG. It's [chartered](http://www.w3.org/2017/dxwg/charter) to:

1. extend the Data Catalogue Vocabulary ([DCAT](https://www.w3.org/TR/vocab-dcat/))  in the light of experience of places such as data.gov.uk;
2. define what is meant by a profile (think of the EC's DCAT-AP and its national variants) and how to publish them for reading by machines and humans;
3. set out how to do content negotiation by profile, meaning that a client can make a request for (meta)data with a list of preferred profiles (again, think DCAT-AP as first preference, then maybe DCAT core as a second choice).

One can imagine something like a UK public sector profile? Then systems can have that as a first preference with other profiles as fall backs.

Both HMG (effectively GDS) and TNA are W3C Members and therefore may join this work as of right. Everything is being done in public and so anyone may contribute to the discussion.

**Comment by Lawrence-G** [comment]
closing as there has been no further comment on this suggestion
