### ISSUE TITLE
Persistent identifiers for public government documents

### ISSUE THREAD

**Issue by RachaelKotarski** [alphagov/tech-and-data-standards#43]
# Create A Challenge

## Title
Persistent identifiers for public government documents

## Category
- [X] Data
- [X] Document
- [X] Technical
- [ ] Other Suggestions

## Challenge Owner
Data services and content lead at the British Library. 
Manage the DataCite UK service, which makes Digital Object Identifiers (DOIs) available to UK organisations.

## Short Description
Assigning resolvable, globally unique and persistent identifiers, such as Digital Object Identifiers (DOIs) to public government documents (reports, data, other papers) allows them to be cited in a stable and trusted way, particularly within an academic context. This supports trust in the research itself.

## User Need
Standard web addresses as URLs used in academic citations are prone to link rot (see: [https://doi.org/10.1371/journal.pone.0115253](https://doi.org/10.1371/journal.pone.0115253)), which reduces the ability to verify claims in the research. This also applies to government documents cited with URLs in the literature, and so undermines use of government documents in academia. 

More widely, all users find it hard to keep track of the location of any given document as it moves around the government's web estate over the long-term.

## Expected Benefits
Resolvable, persistent identifiers like DOIs applied to government documents will ensure stable links. Researchers will be confident that citations to government reports and data found in the literature will work, and content they reference will be available for the long-term. DOIs are well-recognised within the research community, as they have been used to cite online material for more than 15 years. 

The additional layers of governance that come with use of identifiers such as DOIs ensure that all kinds of user will be able to find and access government documents via the same URL no matter where on the government's web estate the item is hosted over time.

Globally unique persistent identifiers will also enable government to see how each document is used. The use of each report can be more easily distinguished from its versions. Identifiers such as DOIs allow the tracking of usage metrics such as Altmetrics ([http://altmetrics.org/manifesto/](http://altmetrics.org/manifesto/)) and with services such as DataCite's Event Data ([https://eventdata.datacite.org/](https://eventdata.datacite.org/)). 

## Functional Needs
Users need to be provided a persistent, trustworthy and globally unique way of referring to public government documents.
Government needs to be able to track the academic use of those documents.

**Comment by stevenjmesser** [comment]
It's GOV.UK policy to make sure that [no links are left behind](https://gds.blog.gov.uk/2012/10/11/no-link-left-behind/), redirecting where appropriate and not recycling URLs. However, as the number of URLs grows, having a number-based (or similar) URI would be helpful.

**Comment by Lawrence-G** [comment]
A new challenge #75 has suggested DOI as a possible solution to this issue.
