### ISSUE TITLE
Word Documents from partner organisations

### ISSUE THREAD

**Issue by edent** [alphagov/tech-and-data-standards#44]
Raised by @BenLaurie on Twitter

> I'd love to read all about it but all your docs are in Word format.

https://twitter.com/BenLaurie/status/870867721952645121

The .docx files in question are from https://www.riscs.org.uk/

* https://www.riscs.org.uk/wp-content/uploads/2017/02/Write-Up-Developer-Centred-Security-Workshop-24Nov16.docx
* https://www.riscs.org.uk/wp-content/uploads/2017/02/Developer-Centred-Security-Call.docx

RISCS is *funded* by NCSC, [but is run by UCL](https://www.ncsc.gov.uk/information/research-institutes).

An open question to our community - should we encourage our partners to use open standards? Should we *require* it? How would we enforce this?

**Comment by oughnic** [comment]
I have no concern with ISO/IEC 29500 as an alternative so long as ISO/IEC 26300 is offered as well.
Current policy is that UK government (including GCHQ) uses open standards, including ISO/IEC 26300, and that spend-control should be the lever.  This should include outsourced services such as RISCS where the standard is specified through a contract.
