### ISSUE TITLE
Updated Open Contracting Data Standard recommendation to version 1.1

### ISSUE THREAD

**Issue by timgdavies** [alphagov/tech-and-data-standards#45]
The Standards Hub currently recommends [Version 1.0 of the Open Contracting Data Standard](https://www.gov.uk/government/publications/open-standards-for-government/open-contracting-data-standard-profile).

[Version 1.1 has recently been released](http://standard.open-contracting.org/latest/en/schema/changelog/)

What would be the process to consider updating the recommendation to suggest use of version 1.1?

**Comment by Lawrence-G** [comment]
The new version was recommended to the Open Standards Board and accepted at the meeting last week. The [published profile](https://www.gov.uk/government/publications/open-standards-for-government/open-contracting-data-standard-profile) will be updated as soon a possible.

**Comment by timgdavies** [comment]
Now that is responsive! Good to hear - thanks.

**Comment by Lawrence-G** [comment]
profile now updated to v1.1
