### ISSUE TITLE
Home Office Not Adopting ODF Internally

### ISSUE THREAD

**Issue by denisemcdoogal** [alphagov/tech-and-data-standards#46]
Home Office Not Adopting ODF Internally

## Summary
> The Home Office is Not Adopting ODF Internally - despite published commitments to do so. GDS opens standards process has stopped chasing to ensure it happens.

[https://www.gov.uk/government/publications/home-office-open-document-format-adoption-plan/home-office-open-document-format-adoption-plan](https://www.gov.uk/government/publications/home-office-open-document-format-adoption-plan/home-office-open-document-format-adoption-plan)

## Category
- [ ] Data
- [*] Document
- [ ] Technical
- [ ] Other Suggestions

## Problem
> The Home Office, like many other central government departments, published plans to phase adoption of the mandatory ODF open standard. 

Here are the plans: [https://www.gov.uk/government/publications/home-office-open-document-format-adoption-plan/home-office-open-document-format-adoption-plan](https://www.gov.uk/government/publications/home-office-open-document-format-adoption-plan/home-office-open-document-format-adoption-plan)

Adoption of ODF was not just about giving citizens using government digital services a choice over document formats and software (i.e. not imposing and favouring Microsoft) but also about dismantling the internal lock-in.  That's why the blogs and published plans were forced to include internal adoption.

The Home Office has made zero attempts to adopt ODF.

There is no senior understanding, nor prioritisation, of this published commitment. 

There is no longer any push from GDS / Cabinet Office to ensure departments stick to their plans to phase adoption of ODF internally.

**Comment by kunnington** [comment]
What rubbish.

This religious obsession with open is deluded.

How can you be open source and secure? You can't be both.

Every serious organisation uses Microsoft because it is the processional choice. That's why government departments are still using Windows and Office. That's why the Home Office CIO stopped the planned use of Google Open Source. 

Microsoft is the professional secure and supported choice.

GDS aren't even trying force adoption of Google Open Source because they know the truth.

I bet all senior government people have Microsoft Office on their computers even Apple Macs. Prove me wrong.

**Comment by edent** [comment]
As per our [terms of use](https://github.com/alphagov/open-standards/blob/master/docs/terms.md) an uncivil and misleading comment from user `kunnington` was removed.

**Comment by kunnington** [comment]
you deleted a comment which genuinely challenges your work

now we know how you pretend to work openly

GDS is only interested in good PR news stories

**Comment by edent** [comment]
We've contacted the Home Office and are awaiting a response.

In the meantime, I notice that many (but not all) of their publications are in ODF:

* [Police recorded crime and outcomes open data tables](https://www.gov.uk/government/statistics/police-recorded-crime-open-data-tables) Majority ODS, one CSV.
* [Workforce management information, 2017](https://www.gov.uk/government/publications/workforce-management-information-2017) all ODS.
* [Modern slavery victims: referral and assessment forms](https://www.gov.uk/government/publications/human-trafficking-victims-referral-and-assessment-forms) Majority ODT, two HTML.
* [Counting rules for recorded crime](https://www.gov.uk/government/publications/counting-rules-for-recorded-crime) Majority PDF, also available in ODS.

There are some exceptions:

* [Fire statistics data tables](https://www.gov.uk/government/statistical-data-sets/fire-statistics-data-tables) Majority in XSLX - two datasets in ODS.
* [Country returns guide](https://www.gov.uk/government/publications/country-returns-guide) Only available in XSLX.
* [Drug misuse: findings from the 2016 to 2017 CSEW](https://www.gov.uk/government/statistics/drug-misuse-findings-from-the-2016-to-2017-csew) Majority in PDF, data only in XSLX.

I'll update this issue once I receive a response from the Home Office.

**Comment by Lawrence-G** [comment]
Some evidence that the situation has improved. 
country returns https://www.gov.uk/government/publications/country-returns-guide
and 
Fires statistics https://www.gov.uk/government/statistical-data-sets/fire-statistics-incident-level-datasets
now in ODS format
I'm closing this issue but will continue to monitor situation.
