### ISSUE TITLE
Clarification for ETRS89 as a Point Location

### ISSUE THREAD

**Issue by PaulDav** [alphagov/tech-and-data-standards#53]
The adopted standard for representing a Point Location is to use ETRS89 ( https://www.gov.uk/government/publications/open-standards-for-government/exchange-of-location-point )

However, a number of councils have come back to ask ‘which flavour of ETRS89 to use’, as GIS systems which support an export to ETRS89 typically offer many options.

 There are at least 25 different versions of ETRS 1989 
 
•	ETRS 1989 DKTM1 to M5;
•	Lots which relate to different countries (there are five different ETRS 1989’s for Poland alone!);
•	ETRS  1989 UWPP 1992;
•	ETRS 1989 UWPP 2000 PAS 5 to PAS 8

Advice from Ordnance Survey is to use EPSG::4258 (or http://www.opengis.net/def/crs/EPSG/0/4258), because that is what is required by the European Commission.

Can the HMG guidance be reviewed and improved with this in mind?

**Comment by edent** [comment]
Thanks for this Paul. Do you have a source of the advice of EPSG::4258 that we can point to?
The only thing I can find is https://www.ordnancesurvey.co.uk/docs/support/guide-coordinate-systems-great-britain.pdf
Will make the update to the page once we have an authoritative source.

**Comment by edent** [comment]
From an email

> The UK’s guidance on INSPIRE is at https://data.gov.uk/location/inspire-tools, but that doesn’t directly include anything specific, merely mentioning the EPSG registry of spatial reference systems. You have to drill right down to section 5 of https://data.gov.uk/sites/default/files/library/Download%20Services%20Operational%20Guidance%2C%20v1.1.pdf to find specific guidance, to use the HTTP URI: “2d Geographical coordinate system based on ETRS89 in continental Europe (including the United Kingdom): http://www.opengis.net/def/crs/EPSG/0/4258”

And from https://data.gov.uk/sites/default/files/Coordinate%20Reference%20Systems%20for%20UK%20Location%20-%20INSPIRE%20View%20Service%20v1.1_10.pdf

> UK will adopt the INSPIRE mandated systems for View Services [2] within the UKLII. There are two geographical CRS, one for regions of continental Europe (ETRS89), and one for regions outside of continental Europe (ITRS). It follows that ITRS should also be used for datasets with global reach or where there are existing international standards in place;
> 1. 2d Geographical coordinate system based on ETRS89 in continental Europe (including the United Kingdom) - http://www.opengis.net/def/crs/EPSG/0/4258

We will change to our guidance. 

Old:
> use ETRS89 for the geographical scope of Europe¹ (WGS 84 or other CRS coordinate systems may also be used in addition to this)

New
> use ETRS89 (EPSG::4258)¹ for the geographical scope of Europe² (WGS 84 or other CRS coordinate systems may also be used in addition to this)
> ¹ [UK Location Information Infrastructure Technical Policy Paper: Coordinate Reference Systems for UK Location - INSPIRE View Service V1.1](https://data.gov.uk/sites/default/files/Coordinate%20Reference%20Systems%20for%20UK%20Location%20-%20INSPIRE%20View%20Service%20v1.1_10.pdf)

**Comment by edent** [comment]
We've now updated https://www.gov.uk/government/publications/open-standards-for-government/exchange-of-location-point

New version reads

> use ETRS89 (EPSG::4258) for the geographical scope of Europe. You can also use WGS 84 or other CRS coordinate system in addition to this.

Thanks for pointing this out.  Please let us know if there are any other clarifications we can make.
