### ISSUE TITLE
Web 2.0 for Emergency Care 

### ISSUE THREAD

**Issue by Digitalmatrix2** [alphagov/tech-and-data-standards#55]
## Title
> Disaster response has always been a challenge during and after major disasters due to the impact of disaster itself, the number of organizations and individuals participating in the response[1] and the lack of rapid social networking to support immediate community response. Disaster, regardless of etiology, exceeds the ability of the local community to cope with the event and requires specialized resources from outside the area impacted[2-4]. In a large-scale destructive event, one of the greatest challenges to public health workers and rescuing teams is to have stable and accessible emergency communication systems[5,6]. However, little researches currently exist regarding the use of communication platforms and internet social networks for emergency response.

Emergency response during disasters is often complicated because communication becomes unavailable. The Chi-Chi earthquake in Taiwan and Hurricane Katrina in US have proven that current telephone, radio and television-based emergency response systems are not capable of meeting all of the community-wide information sharing and communication needs of residents and responders during major disasters[7,8]. After 9/11, Preece and Shneiderman et al proposed the concept of community response grids[9] which would allow authorities, residents, and responders to share information, communicate and coordinate activities via internet and mobile communication devices in response to a major disaster. Information technologies has the potential to provide higher capacity and effective communication mechanisms that can reach citizens and government officials simultaneously[

n the case of typhoon disaster in Taiwan, internet social networking and mobile technology were found to be helpful for community residents, professional emergency rescuers, and government agencies in gathering and disseminating real-time information, regarding volunteer recruitment and relief supplies allocation. We noted that if internet tools are to be integrated in the development of emergency response system, the accessibility, accuracy, validity, feasibility, privacy and the scalability of itself should be carefully considered especially in the effort of applying it in resource poor settings.

Summary
## Category
- [ ] Data
- [ ] Document
- [ yes ] Technical
- [ ] Other Suggestions

## Challenge Owner
> Briefly describe yourself.

## Short Description
> A short summary of the user need and expected benefits of this challenge. This summary will be used to help people to spot which challenges are of interest to them.

## User Need
> The user need that this challenge seeks to address, including a description of the types of users it involves.

## Expected Benefits
>In the case of typhoon disaster in Taiwan, internet social networking and mobile technology were found to be helpful for community residents, professional emergency rescuers, and government agencies in gathering and disseminating real-time information, regarding volunteer recruitment and relief supplies allocation. We noted that if internet tools are to be integrated in the development of emergency response system, the accessibility, accuracy, validity, feasibility, privacy and the scalability of itself should be carefully considered especially in the effort of applying it in resource poor settings.

## Functional Needs
> The functional needs that the proposal must address.

**Comment by Lawrence-G** [comment]
Thank you for the interesting challenge suggestion. The use of social media in disaster situations to coordinate relief efforts has had a lot of media attention in recent years. There are articles and papers on how social media, big data and other existing communications channels have been harnessed. An open standard to combine resources could be useful in emergencies, as long as the data infrastructure survives. It may not, however, be a suitable challenge to investigate here from a cross-government standard point of view. Open to views here.

Interestingly a previous challenge for ‘[Public emergency alert messaging](http://webarchive.nationalarchives.gov.uk/20170605143709/https://standards.data.gov.uk/challenge/public-emergency-alert-messaging)’  touched on some of the needs around emergency response and care.
 
The standard suggested, CAP, is used by Google public alerts and has been adopted by a number of nations.

**Comment by Digitalmatrix2** [comment]
Thanks  Lawrence,

Yes that sounds the basis of Pulse Medic. Thanks  for the response quick I will share it with my team.  I hope all is well at alpha gov.

Keep up the good work

Martin Anderson
PNP CC, BscEc, DIpHe Nursing, AutNurPra , ANP, NP, NMP, ENP, TICS
Microsoft Educational Partner
Microsoft Clinical Partner
IBM Clinical Partner
Microsoft Block Chain as a business
Microsoft Azure Developer Benefit Program
IBM Business Blockchain Badge Holder
020 8396 4356 07440787899 ONC
IBM Cloud X2 Badge Holder
IBM Data Science Practitioner
_____________________________
