### ISSUE TITLE
Introduce a PGP signing service at the post office

### ISSUE THREAD

**Issue by DavidNorman** [alphagov/tech-and-data-standards#57]
# PGP signing at the post office

## Category
- [x] Data
- [ ] Document
- [x] Technical
- [ ] Other Suggestions

## Challenge Owner
I am a software engineer of over 25 years experience.

## Short Description
PGP keys are a recognised open, federated, non-centralized standard for security on the internet.  The 'web of trust' ideology relies on people signing each others keys in order to increase the trust the public keys are associated with the individuals that claim to own them.  Key signing parties happen to facilitate this.  However, since the Post Office provides an identity check system for passports and other official documents, it could likewise provide a key signing service.

## User Need
There are many needs for authenticated documents (legal contracts and so on), and for secure document exchange.  When purchasing my last property there was all sorts of pointless and insecure messing around with a so-called secure document service between myself and the mortgage provider.  PGP provides an open, effective and non-centralized way of solving this problem.

## Expected Benefits
People who have PGP keys can have them signed by a trusted public service.

## Functional Needs
A person should be able to go into the Post Office with a passport, driving licence, or whatever is required for the existing identity check service, and have the post office sign their PGP key with a trusted government key. The fee would be the same as for the existing identity check service.

**Comment by edent** [comment]
Hi David,

Thanks for the suggestion.  I agree that digitally signing legal documents can be a frustrating process.  I'm going to ask a few questions to make sure I've fully understood this challenge.

1. How popular are PGP keys in the UK?  I have one (https://keybase.io/edent) but it is rare that I find any person or group who understands how to validate them. Essentially, are there any reliable data on PGP usage in the UK?
2. Does this *have* to be a function of the Post Office? I'm not sure how privatisation affects what the government can ask them to do.  But, for example, it might be something that [GOV.UK Verify](https://www.gov.uk/government/publications/introducing-govuk-verify/introducing-govuk-verify) could provide.
3. Assuming that a service can verify your identity, how does it verify that you own the PGP key?  For example, Keybase makes me post a signed message to prove I control the key. 
4. Are there other digital signing schemes available which would be more suitable? This is a subjective question, I know. But we have to understand what best meets user needs.

Finally, this isn't a question, but more of an explanation.  electronic signatures fall under the [eIDAS regulations](https://ec.europa.eu/digital-single-market/en/trust-services-and-eid).  The relevant UK legislation is [The Electronic Identification and Trust Services for Electronic Transactions Regulations 2016](http://www.legislation.gov.uk/uksi/2016/696/made).

In the UK, eIDAS is [regulated by the ICO](https://ico.org.uk/for-organisations/guide-to-eidas/).  There is also the "[tScheme](http://www.tscheme.org/directory/index.html)" who maintain a directory of accredited electronic signature providers.

It might be the case that, due to legislation, we cannot mandate a specific standard - but I'll need to investigate that further.

Thanks

**Comment by DavidNorman** [comment]
Answers:

1) not very well accepted at all.  however this is partially because there is no support for them from the legal community and the government.  

2) the post office currently provide a service for authenticating photos and identities so that people can get passports and driving licences. this seems like a natural extension of this function.  however, I was unaware of gov.uk verify service, and I think that this would be an ideal place for this function.

3) as i understand it, under the current system the post office looks at some documents, and compares your photo to you (because you are physically there), and then signs the photo which has been presented.  I suggest that you provide the key to them on a memory stick, along with enough documents to show that you own the email address associated with the key (maybe they email you a link and you click through to one of their servers?).

i note that the current mechanism of spreading trust through keys is to attend key signing parties, where people effectively go through the same process, but just with private individuals.

4) i don't know - other than key signing parties. 

perhaps suggesting PGP was putting up a solution rather than a problem to solve.  the reality is that even if i have a X500 style certificate, i suspect that few organizations will accept communication with me using it.  so perhaps the challenge is for the government to mandate standardized digital identity services (and police the providers to ensure that they are not making too much profit providing the identity service).  As to PGP, i personally prefer it to X500 because it is extraordinarily cheap to obtain a certificate, and if I could pay the Post Office £10 to sign it then it would be great. For comparison, an internet based organization charges $60 per year.

so - perhaps what I am really saying is that the government (via gov.uk verify) should become a low cost X.509 / PGP certificate signer.  But mainly that the government should encourage or mandate that organizations like banks, mortgage lenders, solicitors, DVLA, estate agents, insurance providers,  and UK passports should accept an exchange of digitally signed emails as proof of identity - instead of cooking up their own schemes or requiring physical (and less secure) exchanges.

After all - they are mandating an API for bank account access.

**Comment by edent** [comment]
Thanks for this @DavidNorman.  I'm going to give you an explanation of why I think this is not a suitable challenge for us.  I'm also going to give you some good news - I hope.

### The Bad News

Our team - the Open Standards Team in GDS - mostly considers which standards the government should adopt.  Generally, we can not compel businesses to adopt a particular standard when they deal with their customers.

It is my understanding that organisations - including Government - must accept electronically signed documents as though they had been hand signed.

* The [Electronic Communications Act 2000](http://www.legislation.gov.uk/ukpga/2000/7/section/7) says that electronic signatures are as good as "wet" signatures. 
* This discussion of a [Law Society Practice Note](http://www.osborneclarke.com/insights/electronic-signatures-law-society-practice-note-qa/) explains it further.
* There is a lot more detail in the BEIS publication  [Electronic signatures: guide](https://www.gov.uk/government/publications/electronic-signatures).

Essentially, there's nothing stopping a business accepting a document signed with, say, PGP.    Whether they have the technical expertise to verify a signature is another matter.

There are already several companies which provide individuals with some level of digital signing - see http://www.tscheme.org/directory/appserv.html

Our team can not use your idea for selecting an open standard **for government use**.

### The Good News

Electronic signatures periodically pop up as a topic of discussion in Government and in [GOV.UK Verify](https://gov.uk/verify).

For example, should all documents published by the government be signed? If so, would this increase trust?

Should services like Verify provide you with a mechanism to sign your keys? Should it generate keys for you which you can use elsewhere?

We are looking at how we can improve identity services, and whether PKI is usable enough for the general public and businesses.  This is ongoing work.

Personally, I think it would be great if individuals could choose to get a cryptographically signed token which could then be re-used when they interact with businesses.

Thank you so much for raising this challenge. It has provoked a lot of internal discussion.

I am going to keep this issue open for now, to see if anyone else on our standards panels wants to contribute.

**Comment by DavidNorman** [comment]
thanks for all the info. it seems like things are more advanced than I thought.  The 'electronic communications act 2000' seems like a very good start.  That list of organizations is also very interesting. 

i look forward to the day when a solicitor or bank allows me to do a proper electronic signature with a private key (issued for a low cost with a chain of trust to a top level entity which isn't a US company).

and where that can be done in a standard email client or on the command line (as opposed to a weird extension to the PDF reader).

thanks for taking time to discuss my suggestion.

**Comment by rektide** [comment]
I want to tag along here- I'd love for a privacy respecting authentication system to be in place.

As a citizen, I'd like to be able to go online, using whatever handle I have (@rektide) and write a post, or leave a comment online. And I'd like my government to be able to authenticate my claim to the degree I chose. I might want to identify as a citizen of a certain postcode, or region, or the country.

In practice, this might be achievable by letting me a citizen create X509 certificate signing requests with `L=` fields that match my official records, and government agencies signing these requests when I present required authentication material (a valid UK ID card). This service could either be run as a top-level entity, or individual regions and localities could be in charge of running their own certificate authorities that sign these requests.

Unlike the original proposal, this request is not to create an authentication of me precisely (by name). Instead, such a service offering would let me establish that a work signed via this certificate originated from some person in some locality or region or country. This would be useful for combating disinformation online: it would allow citizens, as they interact online, to establish that they are in fact real flesh & blood citizens of different localities, without having to reveal their full identity. If a hotbutton issue comes up, the presence of locality-authenticated posts would let readers have some confidence that the information they are presenting comes from the area it's claimed to come from, that it comes from a legitimate stakeholder.

This is something I've been kicking around in my head for a while now. Recently [mentioned it on Twitter](https://twitter.com/rektide/status/958168934062141441) too. I think it's an important measure for preserving democracy in the online noospheric age.

**Comment by Lawrence-G** [comment]
Closing this issue regarding edent's comments above to lack of activity since.
