### ISSUE TITLE
Update Unicode to new standard

### ISSUE THREAD

**Issue by edent** [alphagov/tech-and-data-standards#59]
Unicode 11 will be released on 2018-06-11 - http://unicode.org/versions/Unicode11.0.0/

This issue is for board members, and other interested parties, to leave comments on whether the Open Standards Team should update the [Cross platform character encoding profile](https://www.gov.uk/government/publications/open-standards-for-government/cross-platform-character-encoding-profile) to support this newer revision of the standard.

[As per the terms of reference, the board operates by consensus](https://github.com/alphagov/open-standards/blob/master/docs/open-standards-board-terms-of-reference.md).  If the majority of the board agrees with this change, or there are no significant objections from the community, the standard will be updated.

## Background

The current standard is for <a rel="external" href="http://www.unicode.org/versions/Unicode6.2.0/">Unicode 6.2</a> and <a rel="external" href="http://www.rfc-base.org/rfc-3629.html">UTF-8</a>.

Unicode 6.2 was released in 2012.  There have been several important changes since then which will be particularly useful for Government.

* [Version 6.3 of the Unicode Standard is a special release focused on delivering significantly improved bidirectional behaviour.](https://www.unicode.org/versions/Unicode6.3.0/)
* [7.0.0 adds new international currency symbols](https://www.unicode.org/versions/Unicode7.0.0/)
* [8.0.0 includes better diversity representation with skintone modifiers and more international currency support](https://www.unicode.org/versions/Unicode8.0.0/)
* [9.0.0 improves compatibility with HTML5 and CSS](https://www.unicode.org/versions/Unicode9.0.0/)
* [10.0.0 better security to reduce spoofing, better international domains, and flags for England, Scotland, and Wales.](https://www.unicode.org/versions/Unicode10.0.0/)

## Impact
There is no perceived negative impact to updating this standard.  Most software will automatically update to support the newer version of Unicode.

Older software will still be able to read documents which use more recent versions of the standard, but newer characters may render as `�` ([Unicode Replacement Character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character))

## Recommendation
It is the Open Standards Team's recommendation that this update be adopted.

**Comment by dwd** [comment]
There have been a number of cases where the Unicode version has been baked into protocol and specifications, most notably the "stringprep" suite used within various internet authentication systems. It seems to be generally acknowledged that this was a bad thing, and wherever possible the latest version of Unicode should be used.

The Cross Platform Character Encoding Profile discusses why UTF-8 and Unicode in general ought to be used, but offers no rationale as to why a specific version of Unicode was picked - I suggest that is because there isn't any particular reason.

I would argue that unless there are particular reasons why a version should be fixed, the mandate ought to be to support:

- The latest version if possible.
- If not, the latest possible version.
- In any event, at least version 6.2 (though I'd be happy with any particular version stipulated as a minimal baseline here)

Also, I can't promise I won't start to nitpick about the term "character" in that document, nor raise eyebrows about the implicit ban on normalising composing characters.

**Comment by edent** [comment]
Thanks @dwd. Our previous reasoning has been that selecting a specific version means that we are not beholden to take an update that may be problematic for our users. 

For example, if V2 of an adopted standard broke backwards compatibility or had other undesirable issues, we wouldn't be forced into accepting it.

I think this is also the approach taken by CAMSS.

**Comment by dwd** [comment]
Hey @edent - yes, that makes sense, but I don't think any specification introduces incompatible changes without some overwhelmingly good reasons.

But moving our specifications to point at the latest Unicode should be the default, at least - agonising over whether to take an update will just mean we fall behind by several versions, as indeed is the case now. Do we really think that someone using Unicode 10 is doing something dangerously wrong?

**Comment by oughnic** [comment]
Hello all

On the “pin a version” or “let it float to the latest” we should take into account Jon Postel’s Robustness Principle.  Be conservative in what you send (pin to a version); be liberal in what you receive (float within backward compatibility).

Nicholas

Nicholas Oughtibridge BSc FBCS CITP
Head of Clinical Data Architecture
0113 397 4296


[cid:image003.png@01D42039.C8676130]

NHS Digital provides information and technology for better health and care.
Find out more about us: www.digital.nhs.uk<http://www.digital.nhs.uk/> | @nhsdigital<https://twitter.com/nhsdigital>



The Management Systems and Data Sharing Audit teams are certified to ISO 9001:2008

[cid:image004.png@01D23F2D.9969C650]

**Comment by ekoner** [comment]
I support the Open Standards Team's recommendation to adopt this update. The benefits of improved securit and accessibility are clear. 

The points raised by @dwd and replies by @edent and @oughnic are important - shall we add these to the agenda for our next meeting?

**Comment by edent** [comment]
Thanks all. Following your positive feedback, we'll update https://www.gov.uk/government/publications/open-standards-for-government/cross-platform-character-encoding-profile and the associated register.

At the next Board meeting, we'll discuss whether we should specify versions in future standards.

@Lawrence-G over to you.

**Comment by edent** [comment]
We've updated the guidance page, the register, and any linked pages.

Thank you all for your contributions.  We've a blog post coming up about whether we should automatically update to new standards.
