### ISSUE TITLE
SAML

### ISSUE THREAD

**Issue by torgo** [alphagov/tech-and-data-standards#6]
Some services being developed are using SAML. How open is SAML and what is our position on it?

**Comment by philandstuff** [comment]
SAML is maintained by [OASIS](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=security).

**Comment by davidillsley** [comment]
I think @adamkcooper represents GDS in the OASIS group.

Thoughts on SAML:
- Its a framework, not a protocol. You need to specify a profile you want to use
- SAML2 WebSSO is broadly supported and used
- GOV.UK Verify is based on a custom profile of SAML2 WebSSO at https://www.gov.uk/government/publications/identity-assurance-hub-service-saml-20-profile
- Its based on XML Signature and Encryption which is very hard to implement correctly, and commonly results in vulnerabilities
- Most of the momentum in industry appears to be towards OpenID Connect which is more modern and a bit simpler

**Comment by adamkcooper** [comment]
Yes, I am a member of the OASIS Security (SAML) Technical Committee. 

For info:
1) SAML is widely implemented and trusted by the public sector (e.g. It is being used by all EU Member States to implement cross-border eID and GOV.UK Verify)
2) SAML is recognised and understood by security experts such as CESG which is essential for accreditation of .GOV systems
3) OpenID Connect is simpler and does have some advantages (e.g. how it handles attribute services)
4) SAML is not going away - it is trusted and supported by established COTS products and specialist security vendors

**Comment by davbo** [comment]
I'm conflicted between being concerned and hopeful that XML DSig and XMLEnc don't have much of a future. This post on the IETF CURDLE (CURves, Deprecating and a Little more Encryption) working group filled me with hope: https://mailarchive.ietf.org/arch/msg/curdle/ZXwHalF83KOEYbsxKZSui9srWug

> Another option may be for the IETF to recognize reality and recommend
> against further use of XMLDigSig/XMLEnc completely.  I.e., "XML Security
> Considered Harmful".

**Comment by gdsamit** [comment]
On a practical level, there are lots of simplistic / partial / unmaintained SAML implementations out there. Anyone implementing or buying a service that claims to be able to act as a SAML identity provider or relying party needs to look carefully at the profile the authors/vendors have chosen to implement and how well they have followed the standard. While this is true of any standard it's pretty critical for SAML given what it's used for.

**Comment by torgo** [comment]
[meta comment] This is exactly the kind of discussion I had hoped to get going in this repo. I'm thinking this could be distilled into a SAML brief of some kind: where we're using it, what advantages it has, what disadvantages and where it's appropriate to use SAML vs. another approach (e.g. openID connect).

**Comment by torgo** [comment]
IPR situation on SAML 2.0 looks good – many statements of patent non-assert and RF license of essential IPR: https://www.oasis-open.org/committees/security/ipr.php

**Comment by Lawrence-G** [comment]
no further requests for SAML based standards
