### ISSUE TITLE
Data Standards for services tackling loneliness

### ISSUE THREAD

**Issue by Lawrence-G** [alphagov/tech-and-data-standards#61]
## Category
- [x] Data
- [ ] Document
- [ ] Technical
- [ ] Other Suggestions

## Challenge Owner
Lawrence Greenwood, technical advisor, Open Standards Team GDS and the cross-government team leading the project.

## Short Description
A request from the [cross-government loneliness team](https://www.gov.uk/government/collections/governments-work-on-tackling-loneliness) to investigate existing data standards that could be used to help people who are in need of support from organisations dealing with loneliness. The type of help could be in many forms, including support groups, sports and social activities, and volunteering opportunities.

The information on support for lonely people is largely on local government and charity websites.

Initial thoughts were for a data schema that could be used in a directory of services to allow users to find the local or national service that could help them or others. Schema.org’s [‘Event](https://schema.org/Event)’ and [‘Organization’](https://schema.org/Organization) schemas may contain the properties that are needed to mark up the entries and allow search engines to find the published information.

## User Need

As a person dealing with loneliness, I need to be able to search for help and receive results that are relevant to me.
As a developer of a service tackling loneliness I need a way to describe elements in a machine readable way.

## Expected Benefits
To support the government's approach to tackling loneliness by improving access to information that can help the citizens affected.
To make relevant content easier to find.
Other benefits from addressing the [issues raised](https://www.gov.uk/government/news/pm-commits-to-government-wide-drive-to-tackle-loneliness) by the Prime Minister in January

## Functional Needs

Machine-readable information on the content of a document
Including:- 
Location of the service
Type of activity
Type of organisation 
Opening times
Age group 

Any others? please make a suggestion

**Comment by puntofisso** [comment]
Can I suggest we get Gaia Marcus involved in this? She's been working on related issues as a freelancer, as the Youth Homelessness Data Bank project lead, and at Barnardo's, so I think she may have some interesting views.

**Comment by edent** [comment]
@puntofisso yes please! Can you point Gaia this way?

**Comment by puntofisso** [comment]
@edent sure - done!

**Comment by BforBen** [comment]
There's a couple of standards that existing in this space which may be relevant:

1. [Open Referral](http://docs.openreferral.org/en/latest/)
2. [LGA Locally Delivered Services](http://e-sd.org/FEbyy/) (PDF download) which links back to the [Local Government Business Model](https://standards.esd.org.uk/LGBM) that links services to needs and circumstances

I'm not sure if the LGA standard has been used yet. Open Referral has been used by a couple of local authorities in the UK and is also used in the US. Code for America has developed [Ohana](https://github.com/codeforamerica/ohana-api) which is a reference implementation of the Open Referral standard.

There's also the Open Eligibility taxonomy which may be on interest too https://about.auntbertha.com/openeligibility

**Comment by MikeThacker1** [comment]
Yes, as Ben says, the LGA has done a lot of work with iStandUK around the Local
Government Business Model <https://standards.esd.org.uk/LGBM>, specifically
associating types of service
<http://id.esd.org.uk/list/englishAndWelshServices> with people's needs
<http://id.esd.org.uk/list/needs> and circumstances
<http://id.esd.org.uk/list/circumstances>

The Service Directory schema
<http://schemas.opendata.esd.org.uk/ServiceDirectory> was developed by
iStandUK (who have representations of the model in other data formats such
as JSON and XML) who looked at OpenReferral and several other pre-existing
standards.  It has been piloted as a way of recording services which are
assigned service types (by manual and automated means). This enables
organisations to use the data to point people to relevant services.

Pilot work was with councils and health providers in the North West.

The LGA's Tim Adams has been working with Government to review how the
model can be applied specifically to loneliness.

Mike

[image: Picture]
*Mike Thacker* *Porism*
Tel: +44 20 7737 0263
Bon Marché Centre, 241–251 Ferndale Road, London SW9 8BJ, England
<http://porism.com/>mike.thacker@porism.com | porism.com
<http://twitter.com/MikeThacker>  <http://plus.google.com/+MikeThacker>
<http://www.linkedin.com/company/porism>

**Comment by LaGaia** [comment]
Hi Edent!
I would be tempted to look at live services that already need to solve this problem: e.g. UK advice finder and see how their schema overlap with the standards suggested above. NCVO will have a lot on service directories, and NESTA did a lot of work in 'below-the-radar' community activity and how you track and document it. Jimmy Tidey might be an interesting person to link to, on that- https://twitter.com/Jimmytidey

I think that more work/conversation is needed on the user need (As a person dealing with loneliness..) and the suggested action - e.g. I'm not sure that ", I need to be able to search for help and receive results that are relevant to me" is an actual user need. It's a suggested solution that carries a lot of assumptions about human behaviour that don't necessarily hold true. 

I'd be tempted to map the existing service provision, and then understand the data standards they are using, offering solutions at that level.

**Comment by pwin** [comment]
EC Core Public Service Vocabulary Application Profile:  https://joinup.ec.europa.eu/release/core-public-service-vocabulary-application-profile/22 imo should be the core approach to cataloguing all services.  We can modify - create a localised application profile - if this is a good thing.  

There are tools to start creating  some assets in this vocabulary:  https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/cpsv-ap-tools 

Using this approach we can then provide approaches to publication using any number of serialisations, including RDFa, JSON/LD, etc

**Comment by edent** [comment]
Thanks for all these helpful comments. We're going to take a look at better understanding user needs.

**Comment by winfried** [comment]
Interesting question and I wonder what the exact scope of it is. The question starts with ‘existing data standards that could be used to help people who are in need of support from organisations dealing with loneliness’ but it quickly converges to a standard describing initiatives dealing with loneliness.

To start with the latter: I would use FHIR as a technical standard for that and look for specialized ontological models/semantic standards to load on top of it. FHIR is flexible to define your own semantic standard or reuse (parts of) other semantic standards. This would make it easy to reuse existing descriptions for organisations and their type and adding additional information to it. In the Netherlands there is right now a strong standardisation in care towards semantic standards on top of FHIR. These may offer a part of the needed functionality, but certainly not all. But any semantic standard can be used there.

But the start of the question is much more interesting. Helping lonely people can be done in much more ways then by pointing them to initiatives that may help them. But to write or select a standard for that, you first need to model ‘tackling loneliness’. One organisation I worked with, modelled ‘loneliness’ as ‘nobody listening to you’. They set up an infrastructure that was optimized to listening to anybody, no matter how distorted their communication was. An other organisation I worked for modelled ‘loneliness’ as ‘the result of an inability to have meaningful communication’. They set up an infrastructure where people with all kind of disabilities (from very practical as having no voice or being in a remote location to very complex as a heavy psychiatric background) to help other people. An other organisation I worked for, modelled ‘loneliness’ as having a secret that is bothering you, they set up an infrastructure where people were free to speak out, even when sharing that secret would lead to big social or legal repercussions in other contexts. Each of these models for ‘tackling loneliness’ can be translated into a technical standard tailored to that model. And often there are existing standards already providing the needed functionality.

Right now I am involved in a project developing a standard stack for the social aspects of care and health. It focusses on the contextuality of information, the process of gaining trust in relations and the possibility to create multiple public faces of yourself, so you can invite people to contact you on certain attributes of yourself and leaving out other attributes. This project is backed by the Dutch ministry of Health. If I would have to give this projects take on loneliness, then I would say: “the result of not having a place to share meaningful aspects of your life”.

So if you don’t interpret this question as ‘finding organisations that are dealing with loneliness’ but as ‘supporting the processes needed to deal with loneliness’ then there are lots of interesting possibilities, but then you first need to make clear on what processes you are exactly talking about...

**Comment by Lawrence-G** [comment]
This challenge has been superseded issue 77 by https://github.com/alphagov/open-standards/issues/77
