### ISSUE TITLE
Data standard for interchange and querying of public services

### ISSUE THREAD

**Issue by charleemg** [alphagov/tech-and-data-standards#77]
Data standard for interchange and querying of public services 
==============================================================

Category
-----------------
Data

Challenge owners
-----------------
**Ben Unsworth** Head of Service Transformation, Essex County Council

To feed back directly on this challenge, or for questions, contact data-standards-authority@digital.cabinet-office.gov.uk

Short description
-----------------

When seeking assistance, users of public and voluntary sector services will find a huge amount of lists, registers, activities and advisors. This can prove difficult to navigate by service users, their carers, and by anyone else working in the public services sector who needs to find reliable information simply and quickly - and ideally from a single source.

A single organisation can have multiple directories itself, and these can have varying quality and richness. Data quality issues can also make organisations or even separate departments within them feel the need to create their own directories, instead of reusing existing ones from other places.

This can all lead to information that is not reliable, timely or complete enough to recommend services quickly, leading to delayed action by having to carry out further research.

This challenge seeks to find an agreed standard for directories of human services data that helps users find trusted, specific and personalised search results that are appropriate to where people live and what they need, in the time they have available. This standard seeks to cut down on long lists of potential service providers and reduce time people spend in finding the help they need.

The [Open Referral UK data standard](https://openreferraluk.org/) - a UK extension of the Open Referral standard - is already a very strong example of a possible standard, but we'd like to hear about other standards, or possible revisions of existing standards, to review during the consultation process.

User need
---------

The basic user need for this standard is to make relevant content easier to find. The [Adur & Worthing Councils OpenCommunity Beta](https://www.digitalmarketplace.service.gov.uk/digital-outcomes-and-specialists/opportunities/13383) for adopting the Open Referral UK data standard provides a good range of example user needs:

-   As someone seeking information, I need to know what services are available locally, so that I can meet my health, care, and other needs

-   As the admin of a service directory, I need to publish data so that it is searchable, and easily integrated as a data service

-   As a service provider, I want to update my details once, so people and organisations can easily access what I provide

-   As a national provider, I want to access local service directories, including integrations as a data service

-   As a developer, I need to connect to data about local services, so that I can build useful services

-   As a service owner, I need technical and governance support, so that I can successfully implement the Open Referral UK data standard

-   As a link worker I need to be able to identify services that meet my clients' needs for which they are eligible

Expected benefits
-----------------

We expect a good standard to:

-   Define a single data structure with consistent definitions to be used by all stakeholders

-   Define what data elements make up a rich service record that is effective for users or clients to query the service's suitability

-   Enable non-proprietary means of interchanging data between software products with minimum cost and vendor tie-in

-   Provide a simple language for querying service directories that can be adopted by service finder applications, independent of who is publishing the data

We are looking for a standard that is compatible with UK-specific requirements. It should define the structure for human services data delivered primarily by local authorities, solely or in conjunction with other partners across the wider public or third sectors, as well as across central government and devolved administrations.

Functional needs
----------------

The standard should provide the name and organisation delivering each service. It should indicate how the service is accessed (for example online, drop-in, referral or home visit) and provide links and/or contact details to help people gain easy access to the service.

The standard should define the following data entities for rich service information:

-   Service types

-   Eligibility types for service users

-   Eligibility constraints due to a user's demographic profile or location

-   Costs

-   Schedules

-   Locations

-   Location accessibility

-   Reviews and/or endorsements by official organisations

The standard should permit use of any taxonomies of terms for types of service, organisation, eligibility, cost and other elements. Well-managed national and international taxonomies should also be encouraged.

The standard should define machine-readable means of:

-   Extracting a full list of services

-   Extracting full details of each service

-   Querying services to find those matching most common selection criteria

The standard should be maintained in a way that gives confidence in its longevity, providing for incremental improvements that result from a consensus amongst its users.

Prerequisites
-------------

The standard must be interoperable with other relevant standards, meaning it has to:

-   adhere to existing [metadata standards guidance](https://www.gov.uk/government/collections/metadata-standards-for-sharing-and-publishing-data), reference data best practice and in particular [guidance already issued in the description of geospatial data](https://www.gov.uk/government/collections/best-practice-guidance-and-tools-for-geospatial-data-managers) (for example, in service locations)

follow [personal and organisational identity standards](https://www.gov.uk/government/collections/identity-proofing-and-authentication) (for example, when identifying citizens and service providers within the referral process)

**Comment by edent** [comment]
Blog published at https://dataingovernment.blog.gov.uk/2021/04/28/vulnerable-people-services-data-standard/

**Comment by thill-odi** [comment]
As part of the [Open Data Institute](https://theodi.org/)'s work on the [OpenActive](https://www.openactive.io/) family of standards, we've investigated OpenActive's relevance to the domains of social prescribing and referral more generally - areas which have significant overlaps with the area you're aiming to address here. In particular, we commissioned some research (delivered by [Digital Gaps](https://digitalgaps.co.uk/) and [porism](https://porism.com/) last month) into common data-related barriers to referral.

The outputs of this research are publicly available on a [Coda site](https://coda.io/d/Enabling-Social-Prescribing_dt8GA64rhKt/Welcome_suhqz#_luyId). Though focused in the main specifically on OpenActive, I suspect you'll find almost everything in the research of at least some value.

Of particular relevance, however, might be: 

* the [executive summary](https://coda.io/d/Enabling-Social-Prescribing_dt8GA64rhKt/Executive-Summary_sujV9#_luFVF) and [Research Findings Report](https://coda.io/d/Enabling-Social-Prescribing_dt8GA64rhKt/Research-Findings-Report_surth#_lu7g8) for a broad overview
* the [technical research](https://coda.io/d/Enabling-Social-Prescribing_dt8GA64rhKt/Technical-Research_su1Af#_lusEu) sections on alignment with OpenReferral UK and taxonomies
*  the overview of [other ongoing research](https://coda.io/d/Enabling-Social-Prescribing_dt8GA64rhKt/Wider-research-User-research_su4o7#_luqt0) in this area, including [OpenReferral UK pilot implementations](https://coda.io/d/Enabling-Social-Prescribing_dt8GA64rhKt/Open-Community-MCHLG_suobv#_lu4_f)

In addition OpenActive standards may be of interest in their own right, in particular the [Accessibility](https://tutorials.openactive.io/accessibility/) standard, which, while needing further consultation, may prove useful beyond the original physical-activity-facility use-case it was originally developed for.

**Comment by MikeThacker1** [comment]
The work referenced by @thill-odi includes a [technical review of OpenActive's suitability for social prescribing](https://docs.google.com/document/d/1WXzBByZ5VPSJ3jkxBBKmHK8cGh5XlbKKkdFGXr2KU8M/edit?usp=sharing). It identifies some areas where OpenActive could be extended from Open Referral UK (ORUK) learning and some areas where both standards would benefit from small incremental improvements to help social prescribing.

ORUK has a wider scope than OpenActive and ORUK makes provision for some attributes (like some service eligibility constraints) that tend not to apply to the sports and wellbeing activities for which OpenActive is designed.

[The Open Referral API query tool](https://tools.openreferraluk.org/ApiQuery/?endpoint=https://api.porism.com/ServiceDirectoryServiceOpenActiveAggregated&execute=true) implements an [open-source transformation](https://github.com/OpenReferralUK/human-services/tree/master/Utilities/OpenActiveFireHose) of OpenActive data to the Open Referral UK format so it can be combined with ORUK feeds such as those from Bristol, Blackburn, Elmbridge and Hull exposed by the tool.

So ORUK is the obvious/strong candidate for this challenge, building on years of implementation in the US since 2014. OpenActive sports data can be transformed into ORUK format. 

Within a couple of weeks, the revised [OpenReferralUK site](https://openreferraluk.org/) will be launched with a bunch of case studies and adoption guidance.

**Comment by stevenbrandwood** [comment]
Standard address and location data is supported by the GDS Open Standards Board mandate to use Unique Property Reference Numbers (UPRNs) - https://www.gov.uk/government/publications/open-standards-for-government/identifying-property-and-street-information
Bringing service data together should be underpinned by this standard - further information can be found at www.geoplace.co.uk

**Comment by MikeThacker1** [comment]
@stevenbrandwood Open Referral UK extends the international Open Referral standard though it does not change the location and address parts which include fields for latitude, longitude and address with "postal_code". I'm not aware of an existing standard for services for which the UPRN is an integral part. Of course, not all services are associated with a physical location - for example they might be online or delivered at someone's home.

I see that UPRN has already been requested as an addition to the UK extension of Open Referral UK - [see here](https://forum.openreferraluk.org/t/location-tables-and-uprn/79). It will therefore be considered for the next version upgrade.

I understand that for use in open data the address associated with a UPRN needs to have been sourced separately from the licensed address data.

**Comment by emilymacloud** [comment]
Help-seekers find it challenging to access the right support at the right time. For advice services, the landscape is no simpler to navigate.  
 
Current Projects (that may be relevant): 
- Access Social Care have been leading a [data collaboration project](https://static1.squarespace.com/static/5f2160ae3e84ef21653b8190/t/60997ab744c26c20032a20d2/1620671162679/Helplines+Data+Collaboration+Group+-+Findings+May+2021.pdf) in partnership with helplines from Royal Mencap Society, Age UK, Carers UK and Independent Age.   
- London Plus attempted to undertake a similar initiative with regards to Disability Standards. An update about that work is available [here](https://londonplus.org/news/disability-data-standards-working-group).
- [LIST](https://taxonomy.legal/) (US-based) is a taxonomy of legal issues, needs, and situations that people may face. It matches people’s life situations to standard legal terms and codes.
- [My Pickle](https://mypickle.org/) is a crowd-sourced platform that is helping people find help fast.  

Lessons Learned: 
- Recognise the influence of funders and the impact of having variation at the local and national level of the type of information funders ask for.  There are various initiatives where funders are starting to work together to standardise the questions they ask (although a lot of this work is taking place within London).  However, there are also many funders that aren't engaging with these types of discussion and will set the tone for what needs to be provided in monitoring and evaluation evidence, which links back to data and how this structured. Any Standard should reflect the outputs of these discussions as well as making the case for having better data standards and sharing with funders not engaging in these discussions. 
- Be clear about the purpose behind the standard. For example, there are local specific initiatives e.g. social prescribing, which to some extent dictate the taxonomy that will be used when describing activities, services, health conditions and so on, particularly for cross-agency working and then there are other regional/national initiatives that attempt to map the sector to establish the level of need and may use a different taxonomy for this purpose. 
- Culture and compliance: many organisations, particularly small organisations, are suspicious of how data will be used. There need to be adequate safeguards in place e.g. data sharing agreements that set out clear purposes for sharing data and keeping it safe, as well as mechanisms to ensure that data is valid and accurate. 
- Who will feed into the approach? Larger organisations with more time and expertise are more likely to have an opinion than smaller organisations that are less experienced in working with data. Many small organisations are embedded within their community and will have information about local need and the work they are doing. Not all of these organisations are formally registered as charities or ‘visible’, many are Below-the-Radar. The discussions need to engage with small organisations as well as larger ones. 
- Ensure there is a ‘bottom-up’ approach that allows organisations to co-design the Standard. Many of the small organisations that make up the voluntary sector are run by volunteers, or have a small paid time staff without any expertise in data / CRM / monitoring etc.  Many are already stretched or lacking in capacity to take on additional work like this and many will have already invested in their own systems for their own purposes and used whatever taxonomy made sense to them and their funders.   
- Capacity: There is a lot of work that needs to be done, particularly with small groups, to build capacity, skill and knowledge to collect and use data effectively. This reflects at all levels of the organisation from staff and management through to trustees. Any development of a Standard should be embedded within a strategy that provides adequate support and resourcing for the sector.  
- Implementation: Where service providers use similar systems, it is prudent that the relevant CRM providers are involved at the appropriate stage and take appropriate action to conform their systems to the Standard once reached.

**Comment by stevenbrandwood** [comment]
> @stevenbrandwood Open Referral UK extends the international Open Referral standard though it does not change the location and address parts which include fields for latitude, longitude and address with "postal_code". I'm not aware of an existing standard for services for which the UPRN is an integral part. Of course, not all services are associated with a physical location - for example they might be online or delivered at someone's home.
> 
> I see that UPRN has already been requested as an addition to the UK extension of Open Referral UK - [see here](https://forum.openreferraluk.org/t/location-tables-and-uprn/79). It will therefore be considered for the next version upgrade.
> 
> I understand that for use in open data the address associated with a UPRN needs to have been sourced separately from the licensed address data.

Thanks for the clarification Mike - happy to discuss further if that helps

**Comment by MikeThacker1** [comment]
@emilymacloud there's some really useful content in your post.

From the projects you listed I can't see any recommended data structures or data interchange mechanisms (such as Application Programming Interfaces). If you're aware of any that you consider more suitable than Open Referral UK do let us know. Regarding accessibility, I've not seen much beyond the recommendation of a basic taxonomy for uncontentious location accessibility points like "hearing loops" so it would be good to know if London Plus has a concrete data standard.

Open Referral UK (ORUK), extending Open Referral which was introduced in the USA in 2014, has a data structure that should accommodate the requirements of most local initiatives. Very little of the core standard is mandated. "Application profiles" can be used to define the elements expected for specific purposes, such as social prescribing.

ORUK is agnostic when it comes to taxonomies. There is some [guidance on taxonomies here](https://developers.openreferraluk.org/UseOfTaxonomies/). I think there's separate work needed still to settle on the best taxonomies and mappings for specific purposes. I'd argue that any taxonomy used should be open and published according to the [SKOS standard](https://www.w3.org/2004/02/skos/) - but that's separate from this challenge for a standard.

> Where service providers use similar systems, it is prudent that the relevant CRM providers are involved at the appropriate stage and take appropriate action to conform their systems to the Standard once reached.

Absolutely. The [ORUK case studies page](https://openreferraluk.org/community/case-studies) has contributions from local authorities, an Integrated Care System, service directory suppliers and tools providers that have implemented the standard. Three suppliers: FutureGov, Public Partnerships and Placecube have directory products with standard compliant APIs.

**Comment by instantiator** [comment]
[Police Rewired](https://policerewired.org) have been approached by a couple of police services who are developing tools to allow them to make referral decisions as and when they encounter people with needs.

There are 2 main use cases that we looked at:

1. Front-line staff encounter a person with need to be referred for any reason when going about their work. In addition to continuing with their current priorities, they wish to be able to make an on the spot referral to help that person connect with an appropriate support service. This use case generalises well to contexts outside of policing, too.

1. Front-line staff encounter a person as they pass through custody. Arrestees are offered a referral, although the options are limited and there's still very little time for discovery of new services.

Anecdotally, services seem to operate using a short list of potential referral services, or specialised teams for a limited number of positive interventions - although pathways for referral to those policing teams were not always known to police officers or staff.

Common characteristics of both use cases:

* A need to make a positive intervention under time pressure.
* No easy way to discover or rank appropriate services by relevance.

Our community did some early, informal work on this and determined that the existence of directories would help to build tools that could quickly sift through services to find the most appropriate referral options (where appropriateness could be considered a combination of vicinity, opening hours, specialities and capacity).

We explored use of [charitybase.uk](https://charitybase.uk/), but found that although this provided the most complete set of organisations, it wasn't trivial to determine the referral paths or filter by specialisms that each could provide.

We looked at the OpenReferral [HSDS](https://docs.openreferral.org/en/latest/hsds/) and determined that it could meet many more of those requirements, but as yet no directories existed that we were aware of.

We believe that adoption of an open standard that can meet these needs is the first step towards the development of directories - either privately held by front-line services, or (more productively) openly operated and consumable by those services.

This, in turn, could enable those use cases presented above - allowing police services (and other front-line organisations) to build tools that can help them to make referral decisions quickly.

We also believe that adoption of a common standard will help to lower the cost of building operational solutions. There are 43 police services across the UK and a common standard should allow them to build a single tool, so avoiding duplication of effort.

**Comment by CDivers** [comment]
Hi,

Since 2019 and with assistance from over 200 volunteers across the UK, My Pickle has created the UK’s largest National Support Database. Access to this Support Database is available free to the general public at [mypickle.org](https://mypickle.org/). 

The website is designed to cut through the noise online and point anyone facing crisis in the right direction by:

- Signposting support resources across all life issues that are available nationwide across England and/or Scotland / Wales / Northern Ireland
- Ensuring resources can be trusted and are kept up to date through strict vetting processes and data controls 
- Operating without commercial bias affecting decisions whether to include support resources in the database

**Data Quality**

This is incredibly important to us. Anyone from the public can suggest a national support resource for inclusion to the site. All content is pre-moderated. 

As a volunteer-driven initiative our trained Researchers can help source and vet resources. Our pre-publish Quality Assurance (QA) processes involve two independent reviews over each resource.

Our data quality control framework has over 100 data quality controls spanning two areas: 

- Suitability: including accreditation, appropriateness, authority, ethical, quality, term, specific, unique, up to date.
- Data structure: including accuracy, objectivity and validation. 

There is additional information on the resources not currently shown on the front-end including accessibility.

**API / Collaboration**

Our Support Database will soon be available via API. Also happy to input / co-create a solution where local services /databases can be brought together. Please feel free to get in touch cat@mypickle.org

@emilymacloud @MikeThacker1 really nice to meet you over the past couple weeks.

**Comment by MikeThacker1** [comment]
> We looked at the OpenReferral [HSDS](https://docs.openreferral.org/en/latest/hsds/) and determined that it could meet many more of those requirements, but as yet no directories existed that we were aware of.

@instantiator there _are_ directories that comply with the UK extension of Open Referral HSDS as described by Open Referral UK [case studies](https://openreferraluk.org/community/case-studies) and shown by API endpoints in the [API Query Tool](https://tools.openreferraluk.org/ApiQuery/). We're developing a dashboard of API feeds so you can see more clearly where they can be accessed and how much of the standard they support.

There's a long way to go before we have the coverage that Police Rewired might need, but the point of an approved standard (hopefully Open Referral UK) is to the many directories interoperable, building in the lessons of Open referral HSDS.

**Comment by Tim-Adams-LGA** [comment]
I am a programme manager at the Local Government Association, leading on nationally coordinated projects to encourage and help local government make better use of the data they collect, hold and manage. This includes data standards, resources, analysis, sharing, governance, publishing, protecting. Over my twenty years at the LGA we have run many initiatives and developed substantial guidance, tools, knowhow and support to help to progress better understanding and use of local data. We make a big push to open data wherever we can.

I am excited to see the progression of the Open Referral UK data standard for consistent publishing of information about local available services to a consistent and comprehensive specification. We started work in this area a decade ago and started to the work towards this project around five years ago working with colleagues, partners and local authorities in the North West region.

At that time, it became clear that effective discovery and wide-range use about local services would only really take hold if we can develop and agree a single data standard/specification that is well documented and well supported so that all service providers and data publishers can make information available consistently.  This makes it easier for suppliers of systems, platforms of services, websites, apps and related tools to be developed once and then reused nationally with confidence.  The investments can be deployed widely and with little need for constant system changes.

At the LGA in partnership with Cabinet Office, DCMS, MHCLG and a wide number of councils and their systems suppliers, we were able to kick start the consultation and trial process for the new standard.  It formed part of the Government’s commitment to supporting lonely people where we are able to publish, discover and trial presentation of helpful services that can work to offer solutions to loneliness.  A full project report is available online.  The work proved successful in holding diverse services data in a way that was adopted by two commercial suppliers across the three pilot authorities. COVID-19 has changed the scope of services available and so delayed wider rollout but ORUK provides a reliable detailed non-proprietary way of describing services.

The key to better understanding of local public services (be they from public bodies, voluntary groups or the private pioneering organisations and individuals) is to make data available to a consistent specification so that Apps, catalogues, directories, websites and planning to develop the search and matching capabilities once, knowing it will re-work anywhere in the country.  We support this work, the new Open referral UK standard and its accreditation and rollout.  We wish the project well and will be on hand to guide its next steps when they are decided.

**Comment by kathryndingle** [comment]
We working to adopt Open Referral UK's data standard within our app ([Mybestlife.app](mybestlife.app)). The data standard is an opportunity for the whole sector and one we should embrace! 

We are also exploring how we can use schema.org and/or data tagging to improve the availability of charitable service data which will contribute to the Open Referral UK data standard. I am keen to connect with anyone working in this space/interested in this space.

**Comment by stevenbrandwood** [comment]
Hi @kathryndingle, you'll see from the conversation above that I'm no expert on the Open Referral standards, but know a thing or two about addresses and UPRNs if that helps in anyway.  More than happy to talk you through that side of the data.

**Comment by kathryndingle** [comment]
Hi @stevenbrandwood - that sounds great. Let's chat. Do email me on kathryn.dingle@thinknpc.org and we can find a time to chat! Thanks

**Comment by webmink** [comment]
I'm researching this for the OSB discussion and drawing a blank finding the details of origins, governance, maintenance and licensing for this standards profile. I'd welcome pointers - thanks!

**Comment by MikeThacker1** [comment]
@webmink http://openreferraluk.org/ and https://openreferral.org/ have a lot of info on the Open Referral standard.

I believe the documents "Open Referral Proposal_Final" and "Open Referral profile for GOV UK" have been submitted to the Board but I don't know if they're public yet. The first of these should answer all your questions.

**Comment by webmink** [comment]
Thanks Mike - I appreciate you taking the time to reply! I  have read both of those documents but they don't help me in determining if this is an open standard per OSB's definition at https://www.gov.uk/government/publications/open-standards-principles/open-standards-principles#Defining-open-standards

Notably I am looking for evidence that historically and currently this profile has:
- collaboration between all interested parties, not just individual suppliers
- a transparent and published decision-making process that is reviewed by subject matter experts
- a transparent and published feedback and ratification process to ensure quality

I apologise for not being a subject expert in your area - I suspect that's common for OSB members - as this means I need the sort of hand-holding to research and understand matters that are clear to you and other experts. My goal is to arrive at the OSB meeting ready to support the proposal to adopt!

**Comment by MikeThacker1** [comment]
Question 20 in the assessment points to https://docs.google.com/document/d/17cJxF_1P6fafcsFJQERFQifKKc_kPbAKmAXwe2LWDcI/edit#heading=h.jpi5001xplp5 which partly answers the question.

The UK extension was developed by consultation by iStandUK and the LGA. The website has a mailing list to which people can subscribe. Open discussion is via https://forum.openreferraluk.org/ and GitHub issues.

We're working on converging the US and UK processes into one and formalising open version control processes to reflect this.  The standard is driven by mainly public bodies (e.g. local authorities and health social prescribing organisations) not by suppliers, although supplier feedback is very useful for open consultation on enhancements.

**Comment by greggish** [comment]
In case it's helpful to offer historical context: Open Referral's governance processes to date (primarily though not exclusively focused in the US) are described in [this document](https://docs.google.com/document/d/17cJxF_1P6fafcsFJQERFQifKKc_kPbAKmAXwe2LWDcI/edit#heading=h.2rai9ht0wnga), which is linked from our website's About page and also from our github documentation. This describes our approach to representation and feedback solicitation of various stakeholder groups, and our process of setting priorities, reviewing proposals, and making decisions through multiple methods of consultation. We're not a formal SDO but I'm confident we meet the above criteria, and would be glad to answer any other questions you might have. 

(Also I'll note that we're migrating these docs out of Google Docs, converting the text into Markdown and planning to publish it alongside the technical documentation of HSDS in our Github repo and [docs site](https://openreferral.readthedocs.io) in the next update.)

**Comment by webmink** [comment]
Where there's no governance to fall back on, this sort of information is useful, thanks.  It seems OSB needs a process to help proposals gather and present the evidence to support an informally-created standard being treated as open.

**Comment by DidacFB-CDDO** [comment]
As per housekeeping practices we are closing this with the status that Open Referral UK is a recommended standard.
