### ISSUE TITLE
Any Feedback Regarding Job Posting Data Format?

### ISSUE THREAD

**Issue by torgo** [alphagov/tech-and-data-standards#8]
The Open Standards Board has [taken up a question](https://standards.data.gov.uk/challenge/publishing-vacancies-online) of data standards for job posting. It's been proposed to use the [Schema.org schema](http://schema.org/JobPosting) developed for this purpose. To quote the issue:

It has been adopted as a voluntary standard in the US to aid the building of a '[Veterans Job Bank](https://www.whitehouse.gov/blog/2011/11/07/open-innovation-heroes-introducing-veterans-job-bank)' , and has seen some adoption by [vacancy publishers and aggregators](http://www.w3.org/wiki/WebSchemas/JobPostingSchema#Examples_in_the_Wild).

Without getting in the way of the open standards process, I'm just wondering what additional implementer experience there is on using this data schema standard, or indeed other similar schema standards.

**Comment by heathd** [comment]
Seen on x-gov Slack (via @kerin):

https://medium.com/@charlesrt/setting-an-open-standard-for-job-postings-9e548f8fc9bd#.elfr5wifz

https://gist.github.com/charlesrt/75ab9768298cbd2466b7

**Comment by edent** [comment]
This standard has now been approved - https://www.gov.uk/government/publications/open-standards-for-government/publishing-vacancies-online-standards-profile--2
