### ISSUE TITLE
What would a standard for APIs look like?

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [alphagov/tech-and-data-standards#9]
Just picking up on the questions posted by myself and @mattlewis_dvla in #tech-standards on [slack](https://ukgovernmentdigital.slack.com/messages/tech-standards).

To kick things off I'm reposting @mattlewis_dvla's helpful points from slack:
- **Implementation** - Have people rolled their own API Management solution or used a product such as WSO2, Apigee, CA API Management etc.? 
- **Documentation** – We are favouring Swagger 2.0. There is a split between design first or use annotations in the code. What are others doing?
- **Versioning** – Are people using major version number in the URI as favoured by many organisations or starting to support custom media types and gone down the hypermedia route? 
- **Error Codes** – I’d like to compare the set of error codes we are looking to support to get some consistency 
- **Error Payload** – as above, we are looking to return a custom error payload. I can’t find a standard out there for this but would like to be consistent with others 
- **Naming Standards** – adopting camelCase rather than snake_case or hypens. It would be useful to have a common messaging model so that we call the same elements the same things 
- **Authentication/Authorisation** – open APIs will just API Key but this will need to be extended later. We use Verify for View Driving Licence API but we have a lot of data that will be shared with organisations and not private individuals.

Very keen to see where this goes, as we are beginning our API journey at DfE too and would like to get things right!

**Comment by rossjones** [comment]
Are you aware that the swagger 2 spec is now forming the basis for the [OpenAPI initiative](https://openapis.org/)? The specification is currently available at https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md it might cover more than a few of these items?

**Comment by davidread** [comment]
I'll add that requiring an api keys is not a given. It's a huge barrier to casual use, and if you're simple and RESTful there's little need, when you can cache everything. Of course if need to offer intricate uncachable queries then it is another matter. More discussion here: https://opendata.stackexchange.com/questions/774/should-data-apis-require-registration-and-api-keys

**Comment by pmackay** [comment]
@rossjones do you know of any good documentation generators that using a Swagger 2 doc as input?

**Comment by rossjones** [comment]
@pmackay I'm afraid I don't, but would be very interested in you found one.  There are a few mentioned ,like [codegen](https://github.com/swagger-api/swagger-codegen), but I haven't had the opportunity to use any yet.

**Comment by pmackay** [comment]
Re _Naming standards_, related conversation here:

https://github.com/18F/api-standards/issues/40

**Comment by jystewart** [comment]
It feels like this might work better as a set of issues?

At the very least there's "what an API should look like" vs "tools to implement an API", and I suspect documentation probably deserves to be separate too.

I'd personally be inclined to split it up further and have each bullet above as a separate issue. There's definitely lots of interest in versioning and authentication.

**Comment by pmackay** [comment]
@jystewart have split one off :)

**Comment by ivyleavedtoadflax** [comment]
Sounds good.

**Comment by torgo** [comment]
I have created a new issue around API versioning: https://github.com/alphagov/tech-and-data-standards/issues/17

**Comment by edent** [comment]
Now being tracked in #31
